#!/bin/bash

PROFILE_PATH="/home/vagrant/profile-cs.chwnam@gmail.com.json"

LOG_LEVEL="DEBUG"
LOG_FILE="~/lifemotif-diem.log"

DIEM_PATH=~/shared/trusty-generic/lifemotif-diem # Diem script path
PYTHON_PATH=~/.venvs/lifemotif-diem/bin/python   # Python3 path

#### That'is it! Stop editing. ####

SUBCOMMAND=$1

if [[ $SUBCOMMAND == "help" || $SUBCOMMAND == "h" ]]; then
	OPT="--$SUBCOMMAND"
	SUBCOMMAND=""

elif [[ $SUBCOMMAND == "version" || $SUBCOMMAND == "v" ]]; then
	OPT="--$SUBCOMMAND"
	SUBCOMMAND=""

elif [[ $SUBCOMMAND == "create-profile" || $SUBCOMMAND == "cp" ]]; then
	OPT="${@:2}"

else
	OPT="--profile $PROFILE_PATH ${@:2}"
fi

cd $DIEM_PATH  # change directory, path variables may be relative!
$PYTHON_PATH run.py --log-file $LOG_FILE --log-level $LOG_LEVEL $SUBCOMMAND $OPT
